### ISSUE TITLE
Not deleting pvc with claim policy = Delete on pod termination

### ISSUE THREAD

**Issue by joseamey** [metal-stack/csi-driver-lvm#104]
When terminating a StatefulSet that was successfully provisioned by the CSI driver LVM, the associated PVC remains bound and is not deleted by the CSI driver LVM. we use karpenter and the new pod is unable to be scheduled due to the pvc remains in  bound status with the old node dns label , node that not longer exists. 

``` bash
incompatible with provisioner "development-provisioner", daemonset overhead={"cpu":"610m","ephemeral-storage":"1280Mi","memory":"1334Mi","pods":"9"}, incompatible requirements, label "topology.lvm.csi/node" does not have known values
```

```
helm chart version:
name: csi-driver-lvm
version: 0.5.4
description: local persistend storage for lvm
appVersion: v0.5.2
apiVersion: v1
keywords:
- storage
- block-storage
- volume
home: https://metal-stack.io
sources:
- https://github.com/metal-stack

```

**Comment by Gerrit91** [comment]
Hey. As far as I know it's standard behavior of Kubernetes that PVCs of a StatefulSet remain after deletion of a StatefulSet. Do you use any specific feature gates of Kubernetes, which cause this other behavior?

**Comment by Gerrit91** [comment]
Please re-open if necessary.
