### ISSUE TITLE
Support specific disk names for block device

### ISSUE THREAD

**Issue by leonenkoa** [metal-stack/csi-driver-lvm#15]
Use almost the same logic as for LVM, specify disk name (/dev/sda) to be used for block device PVC.
So we can use the whole disk(/dev/sda) as a block device for some pods.

**Comment by mwennrich** [comment]
The whole point of this driver is to use logical volumes, not raw disks.
Besides that, if you want to use a whole disk as block device in a pod, it's probably easier to hostpath-mount /dev into the pod and use that device directly.

**Comment by leonenkoa** [comment]
By the way this driver support block devices and what I suggest to add options to mount those devices as folders in pod and to specify the same as for LVM which physical drive we want to use.
