### ISSUE TITLE
Ephemeral Volume support

### ISSUE THREAD

**Issue by majst01** [metal-stack/csi-driver-lvm#31]
Some use cases require more scratch filesystem space for the application than available via emptydir.
For these type of applications, kubernetes support since 1.16 Ephemeral Volumes:

- https://kubernetes.io/blog/2020/01/21/csi-ephemeral-inline-volumes/
- https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html

csi-driver-host-path does support this: https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/example-ephemeral.md

From reading our code, this seems to be supported as well, but testing it and collecting the required steps in a example-ephemeral.md would be required.

**Comment by mwennrich** [comment]
Example: https://github.com/metal-stack/csi-driver-lvm/blob/master/examples/csi-app-inline.yaml
Integration-tested here: https://github.com/metal-stack/csi-driver-lvm/blob/master/tests/bats/test.bats#L15

**Comment by majst01** [comment]
Ha, i should have had a  closer look, fantastic !
