### ISSUE TITLE
Can csi-driver-lvm work with existing vg?

### ISSUE THREAD

**Issue by kesavkolla** [metal-stack/csi-driver-lvm#37]
I've an existing vg where I want the csi-driver-lvm to create lvs for provisioning. Is it possible to omit the devicepattern and give existing vgname? I don't want csi-driver-lvm to manage the vg instead it should use existing vg. I have pvs already allocated into vg and I use some diskspace in that vg for some other mounts. So I can't give raw devices to csi-driver-lvm. Can someone help me in understanding the behavior of csi-driver-lvm if I give existing vgname and empty devicepattern.

**Comment by majst01** [comment]
On storageclass creation you can specify the vgname to use, see: https://github.com/metal-stack/csi-driver-lvm/blob/master/helm/csi-driver-lvm/templates/csi-lvm-plugin-deployment.yaml#L75

**Comment by Gerrit91** [comment]
Seems to be ok to close this. If not, please re-open.

**Comment by sbahmani** [comment]
I have a existing vg and the link  doesn't available.
