### ISSUE TITLE
/etc/lvm/archive not mapping, possible data loss

### ISSUE THREAD

**Issue by 404notfoundhard** [metal-stack/csi-driver-lvm#83]
Problem:
lost lvs in some situation.
someone has deployed a new pvc.
Now the data cannot be restored from /etc/lvm/backup

as far as I understand, lvs is created using job, but there is no mapping of archives to the host
https://github.com/metal-stack/csi-driver-lvm/blob/master/pkg/lvm/lvm.go#L363

**Comment by majst01** [comment]
Modifying the host from outside kubernetes is strictly discouraged.

**Comment by 404notfoundhard** [comment]
> Modifying the host from outside kubernetes is strictly discouraged.

Outside k8s? What about `/etc/lvm/backup` is it something else?

**Comment by Gerrit91** [comment]
Added this to the host mounts now: https://github.com/metal-stack/helm-charts/pull/104
