### ISSUE TITLE
Operator documentation + resize + adding new volumes

### ISSUE THREAD

**Issue by IxDay** [metal-stack/csi-driver-lvm#90]
I realized that I created a volume far too small for my needs. I created a second one and added to the `devicePattern` option from the Helm chart. However, it seems to not be taken in account. It would be nice to have some operators documentation. I could contribute to this section as well since I think it can help others. For the moment I need guidance on how to proceed. Can someone point me to the right direction (also to help me troubleshoot), maybe it is somewhere but I could not find it.

**Comment by IxDay** [comment]
Ok I found a solution which is going through LVM on the host. Can someone point me to where I can contribute documentation? :smiley:

**Comment by majst01** [comment]
Glad to hear, documentation lives in this repository, any documentation contribution is highly appreciated.

**Comment by Gerrit91** [comment]
If you still want to contribute documentation, please feel free to open a pull request or ask again.
